version: "3"

services:

  front-api:
    image: denperov/owm-task-front-api:${docker_tag}
    ports:
      - "8080:8080"
    networks:
      - auth-api-net
      - items-api-net
      - offers-api-net
    depends_on:
      - auth-api
      - items-api
      - offers-api

  auth-api:
    image: denperov/owm-task-auth-api:${docker_tag}
    ports:
      - "8081:8080"
    networks:
      - auth-api-net
      - auth-db-net
    depends_on:
      - auth-db

  auth-db:
    image: mongo:3.6-jessie
    ports:
      - "10001:27017"
    networks:
      - auth-db-net

  items-api:
    image: denperov/owm-task-items-api:${docker_tag}
    ports:
      - "8082:8080"
    networks:
      - items-api-net
      - items-db-net
    depends_on:
      - items-db

  items-db:
    image: mongo:3.6-jessie
    ports:
      - "10002:27017"
    networks:
      - items-db-net

  offers-api:
    image: denperov/owm-task-offers-api:${docker_tag}
    ports:
      - "8083:8080"
    networks:
      - offers-api-net
      - offers-db-net
      - items-api-net
    depends_on:
      - offers-db
      - items-api

  offers-db:
    image: mongo:3.6-jessie
    ports:
      - "10003:27017"
    networks:
      - offers-db-net

networks:
  auth-db-net:
  auth-api-net:
  items-db-net:
  items-api-net:
  offers-db-net:
  offers-api-net: