// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/denperov/owm-task/libs/types"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// GetUserItems provides a mock function with given fields: ownerID
func (_m *Storage) GetUserItems(ownerID types.Login) []*types.Item {
	ret := _m.Called(ownerID)

	var r0 []*types.Item
	if rf, ok := ret.Get(0).(func(types.Login) []*types.Item); ok {
		r0 = rf(ownerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.Item)
		}
	}

	return r0
}
