// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import types "github.com/denperov/owm-task/libs/types"

// Storage is an autogenerated mock type for the Storage type
type Storage struct {
	mock.Mock
}

// CreateUserItem provides a mock function with given fields: ownerID, item
func (_m *Storage) CreateUserItem(ownerID types.Login, item *types.Item) {
	_m.Called(ownerID, item)
}
